// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBackend.Data;

#nullable disable

namespace MyBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241001235107_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyBackend.Models.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AgeGroupID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityId");

                    b.HasIndex("AgeGroupID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            ActivityId = 1,
                            ActivityName = "Cloud Dough",
                            AgeGroupID = 1,
                            CategoryID = 5,
                            Description = "Making and playing with cloud dough",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 2,
                            ActivityName = "Stacking Blocks",
                            AgeGroupID = 1,
                            CategoryID = 2,
                            Description = "Stacking different types of blocks.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 3,
                            ActivityName = "Animal Sounds",
                            AgeGroupID = 1,
                            CategoryID = 4,
                            Description = "Identifying animal sounds from a book.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 4,
                            ActivityName = "Finger Painting",
                            AgeGroupID = 1,
                            CategoryID = 3,
                            Description = "Creating art using finger paints.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 5,
                            ActivityName = "Bubble Wrap Play",
                            AgeGroupID = 1,
                            CategoryID = 5,
                            Description = "Popping bubble wrap for sensory play.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 6,
                            ActivityName = "Water Play",
                            AgeGroupID = 1,
                            CategoryID = 7,
                            Description = "Splashing and playing with water.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 7,
                            ActivityName = "Sensory Bottles",
                            AgeGroupID = 1,
                            CategoryID = 5,
                            Description = "Exploring sensory bottles filled with different materials.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 8,
                            ActivityName = "Pretend Cooking",
                            AgeGroupID = 1,
                            CategoryID = 1,
                            Description = "Pretend cooking with toy food.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 9,
                            ActivityName = "Making Dragons",
                            AgeGroupID = 2,
                            CategoryID = 4,
                            Description = "Crafting dragons out of toilet roll cardboard.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 10,
                            ActivityName = "Building with Lego",
                            AgeGroupID = 2,
                            CategoryID = 2,
                            Description = "Creating structures with Lego.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 11,
                            ActivityName = "Sticker Collage",
                            AgeGroupID = 2,
                            CategoryID = 3,
                            Description = "Making a collage with various stickers.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 12,
                            ActivityName = "Dress-Up Play",
                            AgeGroupID = 2,
                            CategoryID = 1,
                            Description = "Engaging in dress-up and role play.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 13,
                            ActivityName = "Nature Walk",
                            AgeGroupID = 2,
                            CategoryID = 8,
                            Description = "Collecting natural items during a nature walk.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 14,
                            ActivityName = "Lego Castle",
                            AgeGroupID = 2,
                            CategoryID = 2,
                            Description = "Building a castle with Lego.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 15,
                            ActivityName = "Making Pizza",
                            AgeGroupID = 2,
                            CategoryID = 1,
                            Description = "Pretend making pizza with play dough.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 16,
                            ActivityName = "Obstacle Course",
                            AgeGroupID = 2,
                            CategoryID = 7,
                            Description = "Navigating a simple obstacle course.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 17,
                            ActivityName = "Origami Animals",
                            AgeGroupID = 3,
                            CategoryID = 3,
                            Description = "Folding paper to create animal shapes.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 18,
                            ActivityName = "Volcano Experiment",
                            AgeGroupID = 3,
                            CategoryID = 8,
                            Description = "Creating a baking soda and vinegar volcano.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 19,
                            ActivityName = "Relay Races",
                            AgeGroupID = 3,
                            CategoryID = 6,
                            Description = "Participating in relay races with rules.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 20,
                            ActivityName = "Fantasy Map Making",
                            AgeGroupID = 3,
                            CategoryID = 4,
                            Description = "Creating maps for fantasy adventures.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 21,
                            ActivityName = "Clay Sculpting",
                            AgeGroupID = 3,
                            CategoryID = 3,
                            Description = "Sculpting figures from clay.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 22,
                            ActivityName = "Chess",
                            AgeGroupID = 3,
                            CategoryID = 6,
                            Description = "Learning and playing chess.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 23,
                            ActivityName = "Jump Rope",
                            AgeGroupID = 3,
                            CategoryID = 7,
                            Description = "Jumping rope and playing jump rope games.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 24,
                            ActivityName = "Scavenger Hunt",
                            AgeGroupID = 3,
                            CategoryID = 8,
                            Description = "Organizing a scavenger hunt in the backyard.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 25,
                            ActivityName = "Robot Building",
                            AgeGroupID = 4,
                            CategoryID = 2,
                            Description = "Building simple robots with Lego and motors.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 26,
                            ActivityName = "Watercolor Painting",
                            AgeGroupID = 4,
                            CategoryID = 3,
                            Description = "Creating detailed paintings with watercolors.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 27,
                            ActivityName = "Fantasy Role-Playing",
                            AgeGroupID = 4,
                            CategoryID = 4,
                            Description = "Engaging in complex fantasy role-playing games.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 28,
                            ActivityName = "Story Writing",
                            AgeGroupID = 4,
                            CategoryID = 4,
                            Description = "Writing and illustrating short stories.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 29,
                            ActivityName = "Coding Games",
                            AgeGroupID = 4,
                            CategoryID = 8,
                            Description = "Designing simple games using coding.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 30,
                            ActivityName = "Strategy Board Games",
                            AgeGroupID = 4,
                            CategoryID = 6,
                            Description = "Playing strategy-based board games like Risk.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 31,
                            ActivityName = "Obstacle Challenges",
                            AgeGroupID = 4,
                            CategoryID = 7,
                            Description = "Creating and overcoming physical obstacle challenges.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 32,
                            ActivityName = "Recycled Art",
                            AgeGroupID = 4,
                            CategoryID = 3,
                            Description = "Creating art from recycled materials.",
                            ImageUrl = ""
                        },
                        new
                        {
                            ActivityId = 33,
                            ActivityName = "Drama Skits",
                            AgeGroupID = 4,
                            CategoryID = 1,
                            Description = "Writing and performing short skits.",
                            ImageUrl = ""
                        });
                });

            modelBuilder.Entity("MyBackend.Models.ActivityMaterial", b =>
                {
                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.HasKey("ActivityId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("ActivityMaterials");

                    b.HasData(
                        new
                        {
                            ActivityId = 1,
                            MaterialId = 5
                        },
                        new
                        {
                            ActivityId = 1,
                            MaterialId = 12
                        },
                        new
                        {
                            ActivityId = 2,
                            MaterialId = 1
                        },
                        new
                        {
                            ActivityId = 3,
                            MaterialId = 3
                        },
                        new
                        {
                            ActivityId = 4,
                            MaterialId = 11
                        },
                        new
                        {
                            ActivityId = 4,
                            MaterialId = 8
                        },
                        new
                        {
                            ActivityId = 5,
                            MaterialId = 14
                        },
                        new
                        {
                            ActivityId = 6,
                            MaterialId = 38
                        },
                        new
                        {
                            ActivityId = 7,
                            MaterialId = 46
                        },
                        new
                        {
                            ActivityId = 8,
                            MaterialId = 45
                        },
                        new
                        {
                            ActivityId = 8,
                            MaterialId = 46
                        },
                        new
                        {
                            ActivityId = 8,
                            MaterialId = 47
                        },
                        new
                        {
                            ActivityId = 9,
                            MaterialId = 7
                        },
                        new
                        {
                            ActivityId = 9,
                            MaterialId = 25
                        },
                        new
                        {
                            ActivityId = 9,
                            MaterialId = 9
                        },
                        new
                        {
                            ActivityId = 10,
                            MaterialId = 6
                        },
                        new
                        {
                            ActivityId = 11,
                            MaterialId = 9
                        },
                        new
                        {
                            ActivityId = 11,
                            MaterialId = 10
                        },
                        new
                        {
                            ActivityId = 12,
                            MaterialId = 25
                        },
                        new
                        {
                            ActivityId = 12,
                            MaterialId = 35
                        },
                        new
                        {
                            ActivityId = 13,
                            MaterialId = 46
                        },
                        new
                        {
                            ActivityId = 14,
                            MaterialId = 6
                        },
                        new
                        {
                            ActivityId = 15,
                            MaterialId = 5
                        },
                        new
                        {
                            ActivityId = 15,
                            MaterialId = 38
                        },
                        new
                        {
                            ActivityId = 16,
                            MaterialId = 38
                        },
                        new
                        {
                            ActivityId = 17,
                            MaterialId = 10
                        },
                        new
                        {
                            ActivityId = 18,
                            MaterialId = 43
                        },
                        new
                        {
                            ActivityId = 18,
                            MaterialId = 44
                        },
                        new
                        {
                            ActivityId = 18,
                            MaterialId = 27
                        },
                        new
                        {
                            ActivityId = 18,
                            MaterialId = 25
                        },
                        new
                        {
                            ActivityId = 18,
                            MaterialId = 26
                        },
                        new
                        {
                            ActivityId = 18,
                            MaterialId = 48
                        },
                        new
                        {
                            ActivityId = 18,
                            MaterialId = 49
                        },
                        new
                        {
                            ActivityId = 18,
                            MaterialId = 50
                        },
                        new
                        {
                            ActivityId = 19,
                            MaterialId = 33
                        },
                        new
                        {
                            ActivityId = 20,
                            MaterialId = 10
                        },
                        new
                        {
                            ActivityId = 20,
                            MaterialId = 25
                        },
                        new
                        {
                            ActivityId = 20,
                            MaterialId = 26
                        },
                        new
                        {
                            ActivityId = 20,
                            MaterialId = 27
                        },
                        new
                        {
                            ActivityId = 21,
                            MaterialId = 5
                        },
                        new
                        {
                            ActivityId = 21,
                            MaterialId = 4
                        },
                        new
                        {
                            ActivityId = 22,
                            MaterialId = 2
                        },
                        new
                        {
                            ActivityId = 23,
                            MaterialId = 33
                        },
                        new
                        {
                            ActivityId = 24,
                            MaterialId = 45
                        },
                        new
                        {
                            ActivityId = 24,
                            MaterialId = 46
                        },
                        new
                        {
                            ActivityId = 25,
                            MaterialId = 6
                        },
                        new
                        {
                            ActivityId = 25,
                            MaterialId = 39
                        },
                        new
                        {
                            ActivityId = 26,
                            MaterialId = 11
                        },
                        new
                        {
                            ActivityId = 26,
                            MaterialId = 8
                        },
                        new
                        {
                            ActivityId = 26,
                            MaterialId = 10
                        },
                        new
                        {
                            ActivityId = 27,
                            MaterialId = 35
                        },
                        new
                        {
                            ActivityId = 27,
                            MaterialId = 36
                        },
                        new
                        {
                            ActivityId = 28,
                            MaterialId = 10
                        },
                        new
                        {
                            ActivityId = 28,
                            MaterialId = 8
                        },
                        new
                        {
                            ActivityId = 29,
                            MaterialId = 51
                        },
                        new
                        {
                            ActivityId = 30,
                            MaterialId = 2
                        },
                        new
                        {
                            ActivityId = 31,
                            MaterialId = 45
                        },
                        new
                        {
                            ActivityId = 31,
                            MaterialId = 46
                        },
                        new
                        {
                            ActivityId = 31,
                            MaterialId = 38
                        },
                        new
                        {
                            ActivityId = 32,
                            MaterialId = 45
                        },
                        new
                        {
                            ActivityId = 32,
                            MaterialId = 25
                        },
                        new
                        {
                            ActivityId = 32,
                            MaterialId = 26
                        },
                        new
                        {
                            ActivityId = 32,
                            MaterialId = 27
                        },
                        new
                        {
                            ActivityId = 33,
                            MaterialId = 10
                        },
                        new
                        {
                            ActivityId = 33,
                            MaterialId = 8
                        });
                });

            modelBuilder.Entity("MyBackend.Models.AgeGroup", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("AgeGroups");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Range = "0-2 years"
                        },
                        new
                        {
                            id = 2,
                            Range = "3-5 years"
                        },
                        new
                        {
                            id = 3,
                            Range = "6-8 years"
                        },
                        new
                        {
                            id = 4,
                            Range = "9-12 years"
                        });
                });

            modelBuilder.Entity("MyBackend.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Imaginative Play"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Construction"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Art"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Fantasy"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Sensory"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Games with Rules"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Physical"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Exploration"
                        });
                });

            modelBuilder.Entity("MyBackend.Models.Favourite", b =>
                {
                    b.Property<int>("FavouriteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavouriteID"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FavouriteID");

                    b.HasIndex("ActivityId");

                    b.HasIndex("UserId");

                    b.ToTable("Favourites");

                    b.HasData(
                        new
                        {
                            FavouriteID = 1,
                            ActivityId = 1,
                            UserId = 1
                        },
                        new
                        {
                            FavouriteID = 2,
                            ActivityId = 2,
                            UserId = 1
                        },
                        new
                        {
                            FavouriteID = 3,
                            ActivityId = 3,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("MyBackend.Models.Material", b =>
                {
                    b.Property<int>("MaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialID"));

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialID");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            MaterialID = 1,
                            MaterialName = "Blocks"
                        },
                        new
                        {
                            MaterialID = 2,
                            MaterialName = "Puzzles"
                        },
                        new
                        {
                            MaterialID = 3,
                            MaterialName = "Books"
                        },
                        new
                        {
                            MaterialID = 4,
                            MaterialName = "Art Supplies"
                        },
                        new
                        {
                            MaterialID = 5,
                            MaterialName = "Dough"
                        },
                        new
                        {
                            MaterialID = 6,
                            MaterialName = "Lego"
                        },
                        new
                        {
                            MaterialID = 7,
                            MaterialName = "Cardboard"
                        },
                        new
                        {
                            MaterialID = 8,
                            MaterialName = "Markers"
                        },
                        new
                        {
                            MaterialID = 9,
                            MaterialName = "Stickers"
                        },
                        new
                        {
                            MaterialID = 10,
                            MaterialName = "Paper"
                        },
                        new
                        {
                            MaterialID = 11,
                            MaterialName = "Paint"
                        },
                        new
                        {
                            MaterialID = 12,
                            MaterialName = "Cornflour"
                        },
                        new
                        {
                            MaterialID = 13,
                            MaterialName = "Balloons"
                        },
                        new
                        {
                            MaterialID = 14,
                            MaterialName = "Bubbles"
                        },
                        new
                        {
                            MaterialID = 15,
                            MaterialName = "Rice"
                        },
                        new
                        {
                            MaterialID = 16,
                            MaterialName = "Pasta"
                        },
                        new
                        {
                            MaterialID = 17,
                            MaterialName = "Glitter"
                        },
                        new
                        {
                            MaterialID = 18,
                            MaterialName = "Pom Poms"
                        },
                        new
                        {
                            MaterialID = 19,
                            MaterialName = "Pipe Cleaners"
                        },
                        new
                        {
                            MaterialID = 20,
                            MaterialName = "Cotton Balls"
                        },
                        new
                        {
                            MaterialID = 21,
                            MaterialName = "Feathers"
                        },
                        new
                        {
                            MaterialID = 22,
                            MaterialName = "Buttons"
                        },
                        new
                        {
                            MaterialID = 23,
                            MaterialName = "Beads"
                        },
                        new
                        {
                            MaterialID = 24,
                            MaterialName = "Sequins"
                        },
                        new
                        {
                            MaterialID = 25,
                            MaterialName = "Glue"
                        },
                        new
                        {
                            MaterialID = 26,
                            MaterialName = "Tape"
                        },
                        new
                        {
                            MaterialID = 27,
                            MaterialName = "Scissors"
                        },
                        new
                        {
                            MaterialID = 28,
                            MaterialName = "Hole Punch"
                        },
                        new
                        {
                            MaterialID = 29,
                            MaterialName = "Ruler"
                        },
                        new
                        {
                            MaterialID = 30,
                            MaterialName = "Stapler"
                        },
                        new
                        {
                            MaterialID = 31,
                            MaterialName = "Paper Clips"
                        },
                        new
                        {
                            MaterialID = 32,
                            MaterialName = "Rubber Bands"
                        },
                        new
                        {
                            MaterialID = 33,
                            MaterialName = "String"
                        },
                        new
                        {
                            MaterialID = 34,
                            MaterialName = "Yarn"
                        },
                        new
                        {
                            MaterialID = 35,
                            MaterialName = "Fabric"
                        },
                        new
                        {
                            MaterialID = 36,
                            MaterialName = "Felt"
                        },
                        new
                        {
                            MaterialID = 37,
                            MaterialName = "Foam"
                        },
                        new
                        {
                            MaterialID = 38,
                            MaterialName = "Wood"
                        },
                        new
                        {
                            MaterialID = 39,
                            MaterialName = "Plastic"
                        },
                        new
                        {
                            MaterialID = 40,
                            MaterialName = "Metal"
                        },
                        new
                        {
                            MaterialID = 41,
                            MaterialName = "Glass"
                        },
                        new
                        {
                            MaterialID = 42,
                            MaterialName = "Ceramic"
                        },
                        new
                        {
                            MaterialID = 43,
                            MaterialName = "Paper Mache"
                        },
                        new
                        {
                            MaterialID = 44,
                            MaterialName = "Cardboard"
                        },
                        new
                        {
                            MaterialID = 45,
                            MaterialName = "Recycled Materials"
                        },
                        new
                        {
                            MaterialID = 46,
                            MaterialName = "Natural Materials"
                        },
                        new
                        {
                            MaterialID = 47,
                            MaterialName = "Water"
                        },
                        new
                        {
                            MaterialID = 48,
                            MaterialName = "Baking soda"
                        },
                        new
                        {
                            MaterialID = 49,
                            MaterialName = "Vinegar"
                        },
                        new
                        {
                            MaterialID = 50,
                            MaterialName = "Food coloring"
                        },
                        new
                        {
                            MaterialID = 51,
                            MaterialName = "Computer"
                        });
                });

            modelBuilder.Entity("MyBackend.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "john.doe@example.com",
                            Username = "john_doe"
                        },
                        new
                        {
                            UserID = 2,
                            Email = "jane.smith@example.com",
                            Username = "jane_smith"
                        });
                });

            modelBuilder.Entity("MyBackend.Models.Activity", b =>
                {
                    b.HasOne("MyBackend.Models.AgeGroup", "AgeGroup")
                        .WithMany("Activities")
                        .HasForeignKey("AgeGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyBackend.Models.Category", "Category")
                        .WithMany("Activities")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgeGroup");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyBackend.Models.ActivityMaterial", b =>
                {
                    b.HasOne("MyBackend.Models.Activity", "Activity")
                        .WithMany("ActivityMaterials")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyBackend.Models.Material", "Material")
                        .WithMany("ActivityMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("MyBackend.Models.Favourite", b =>
                {
                    b.HasOne("MyBackend.Models.Activity", "Activity")
                        .WithMany("Favourites")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyBackend.Models.User", "User")
                        .WithMany("Favourites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyBackend.Models.Activity", b =>
                {
                    b.Navigation("ActivityMaterials");

                    b.Navigation("Favourites");
                });

            modelBuilder.Entity("MyBackend.Models.AgeGroup", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("MyBackend.Models.Category", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("MyBackend.Models.Material", b =>
                {
                    b.Navigation("ActivityMaterials");
                });

            modelBuilder.Entity("MyBackend.Models.User", b =>
                {
                    b.Navigation("Favourites");
                });
#pragma warning restore 612, 618
        }
    }
}
